import { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./components/nav/nav";
import "./globals.css";
import Footer from "./components/footer/footer";
import ScrollToTop from "./components/scrollToTop/scrollToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio of  Yassin Samir - Web developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <main
          className="min-h-screen relative mx-auto px-6 sm:px-12 
        lg:max-w-[70rem] xl:max-w-[76rem] 2xl:max-w-[92rem] text-white"
        >
          {children}
        </main>
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}
